### PR TITLE
Load drivers from resources instead of project root

### PR DESCRIPTION
**Pull request by colatkinson**
The webdrivers are stored in the resources folder of the project using the framework, and are extracted to temporary files at runtime. This allows them to be packed into JARs for easy distribution. The project using the framework will be responsible for the installation of the webdrivers, but the framework now uses the same naming scheme as [webdriverextensions-maven-plugin](https://github.com/webdriverextensions/webdriverextensions-maven-plugin), so this is trivially easy.

I incremented the patch number for ease of testing, but I don't know what convention you use for versioning.

### CODE REVIEW

**Comment by ddavison** [comment]
this looks fantastic.. give me until tomorrow to merge it in.

**Comment by colatkinson** [comment]
Any updates on merging this? It'd be cool to be able to pull it in from Maven. No rush though.

**Comment by colatkinson** [comment]
There are 64-bit versions of the drivers available. I hardcoded in 32-bit for simplicity's sake. I agree, though, futureproofing is probably a good move.

How do you think this should be handled? The best solution I can see is packaging both versions of the binaries and deciding which to use at runtime. Can you think of a better way?

**Comment by colatkinson** [comment]
@ddavison I've implemented a simple method to use architecture-appropriate webdrivers if they are present. If not, it will fall back on the 32-bit version. Let me know what you think.

**Pull request merged**
