### PR TITLE
Added support for base-url and path's, changed override order for params

### PR DESCRIPTION
**Pull request by jossjacobo**
Added the support for base url and path to have better integration for CI and multiple staging environments, as well as changing the override order for params to accommodate for this.

### CODE REVIEW

**Comment by ddavison** [comment]
this looks great! give me some time and I'll merge it in.

**Comment by jossjacobo** [comment]
Bump :)

**Comment by ddavison** [comment]
so remind me again what the advantage to using baseUrl was?

before this change, you were able to do something like this:

```default.properties
url=http://test.product.com
```

```Test.java
public void test() {
  navigateTo("/some_sub_url");  // will end up on http://test.product.com/some_sub_url
```

**Comment by jossjacobo** [comment]
Hmm I see your point.

The `base_url` param might not be needed, at the very least it would save you one page load, from `url` to `/some_sub_url`.

I think the main thing I was trying to solve for is being able to do something like `mvn test -DCONDUCTOR_URL='some_enviroment_url'` and have that command override all the test urls, while also having a "cleaner" way of doing `navigateTo()` has part of the `@config`.

As it is right now the Override rules for the url are `test->defaults->jvm`, meaning that everything overrides the `jvm`. Imo it should be `jvm->test->defaults`, where everything can rewrite the `defaults` if you need to for a special case.

**Comment by ddavison** [comment]
i thought i designed it that way?  i could've been totally wrong haha

I thought i designed it:

JVMargs override all
test overrides default  (as you put)  i might be completely wrong.  either way - i've merged it.  thanks :)

**Comment by ddavison** [comment]
released it as version `2.3.0`, but will take some time for maven central to pick up on it.

**Pull request merged**
