### PR TITLE
Custom caps

### PR DESCRIPTION
**Pull request by ashby-bowles**

### CODE REVIEW

**Comment by ddavison** [comment]
hey @ashby-bowles , @jossjacobo @konwinkler !

glad you are finding Conductor to be useful for Willow Tree Apps! also i'm super glad that you are making the source your own!!

upon looking at this change however (i know that this PR was an accident, that's ok), I noticed you aren't abiding by the Apache 2.0 license that I have applied to the project.

Section 4 (c) of the [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0.html) states:

screen shot 2018-09-12 at 7 12 31 pm

please make sure that the copyright notices are left in place of the files belonging to conductor.  you **may** of course change these files and add your own copyright to the source, but please make sure it stays within the limits of the [Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0.html)

**Comment by jossjacobo** [comment]
Hey @ddavison! Yeah we kinda just ran with it and started modifying it to meet our specific needs, thanks for the open source library it's been really helpful :D

That's a fair point, we'll go back and add the copyright notices to all the appropriate files.

Cheers,

**Comment by jossjacobo** [comment]
Also, at some point we wanted to reach out to you and see if there was a possibility of contributing back all of our changes to your original open source project. We've added a lot of great features to make development and CI/CD easier, which I am sure lots of users might find helpful. Supporting 1 open source project together would be better than supporting 2 separately.

**Comment by ddavison** [comment]
awesome!  glad you've found it useful!

> at some point we wanted to reach out to you and see if there was a possibility of contributing back all of our changes to your original open source project

absolutely!  it's been quite a while since i've been able to maintain this project, i wouldn't mind talking about adding Contributor statuses to yourself as well as others on your team to maintain the project, but we can talk about that at some other time.

> Supporting 1 open source project together would be better than supporting 2 separately.

💯 💯 💯 💯 ⭐️

**Pull request closed without merging**
